### ISSUE TITLE
Example Files

### ISSUE THREAD

**Issue by halfagascan** [bebo-dot-dev/m3u-epg-editor#65]
In my attempt at channel/group transforms, using the limited examples, was a failure.
I did not understand the search and replace, what was I searching for, and what was the replacement, until I started reading 
past issues, specifically, in this case issue #47.
In that case there is an example that works.
Thanks
raven

**Comment by bebo-dot-dev** [comment]
Hi there, when the transform feature was originally introduced as a result of https://github.com/bebo-dot-dev/m3u-epg-editor/issues/47 being raised, this feature did not support regular expression transformations in v1.0. Later https://github.com/bebo-dot-dev/m3u-epg-editor/issues/59 was raised and the transform feature was extended to support regular expression transformations. 

It is not mandatory to use regular expressions when using this feature because the python script code is intelligent enough to workout whether you're using a regular expression in this feature or not. In short what works for one person when using this feature with regular expressions will work perfectly well for that first person but the next person will need something else completely different.

I think you're suggesting that it could be useful to somehow expand on how the transform feature generally works, either in [the command line examples](https://github.com/bebo-dot-dev/m3u-epg-editor#sample-usage-calls-urls-intentionally-incomplete) or in [the sample json file](https://github.com/bebo-dot-dev/m3u-epg-editor/blob/master/sample_input_args.json) and if so you could be right. That said I'm not inclined to attempt to offer any regex examples because any supplied sample regular expression will be very specific to only working with specific input data because that's the nature of how regular expressions work. If people need to construct a regular expression to fit m3u input data, there are many online regular expression testing tools to help with that i.e. https://regex101.com

**Comment by halfagascan** [comment]
ok, thanks
closed
